### ISSUE TITLE
progress return back?

### ISSUE THREAD

**Issue by kaiv587hh** [tonyofrancis/Fetch#185]
I try to listen file progress ,then I called 
 mRxFetch.addListener(this);
but when I call 
 mRxFetch.pause(downloadId);
for example :
the callback called
onProgress 30 
pause !!!
 onProgress  60
onPaused 40

onResume 40 

why onProgress 60 > onPause 40 , should onProgress called after pause called ? should the progress return back ? @dougkeen @jacobtabak @tonyofrancis

**Comment by tonyofrancis** [comment]
@kaiv587hh Have you taken a look at the sample app?
1. Configure Fetch and add listeners.
2. Enqueue Download.
3. Check the `download.id` of the download returned in the FetchListener callbacks and update UI accordingly.  

Please share sample code so we can better assist.

**Comment by kaiv587hh** [comment]
here is my server code 
`public class DownloadOpsStub extends IDownloadOps.Stub implements FetchListener {

    private RxFetch mRxFetch;
    private Context mContext;
    private final RemoteCallbackList<IDownloadListener> mDownloadListeners = new RemoteCallbackList<>();
    private final Map<Download,DownloadInfo> mCacheDownloadInfo = new WeakHashMap<>();

    public DownloadOpsStub(Context context){
        this.mContext = context;
        FetchConfiguration fetchConfiguration = new FetchConfiguration.Builder(mContext)
                .setDownloadConcurrentLimit(Runtime.getRuntime().availableProcessors())
                .setHttpDownloader(new OkHttpDownloader())
                .enableLogging(BuildConfig.DEBUG)
                .enableRetryOnNetworkGain(true)
                .enableAutoStart(true)
                .build();
        mRxFetch = RxFetch.Impl.getRxInstance(fetchConfiguration);
    }


    @Override
    public int newRequest(DownloadRequestInfo downloadRequestInfo) throws RemoteException {
        Logger.d("url is %s savePath is %s",downloadRequestInfo.url,downloadRequestInfo.filePath);
        try {
            Request request = new Request(downloadRequestInfo.url,downloadRequestInfo.filePath);
            request.setGroupId(downloadRequestInfo.groupId);
            request.setTag(downloadRequestInfo.tag);
            return mRxFetch
                    .enqueue(request)
                    .asObservable()
                    .compose(RxUtils.applyIo2MainSchedulers())
                    .toFuture()
                    .get()
                    .getId();
        } catch (InterruptedException | ExecutionException e) {
            e.printStackTrace();
        }
        return 0;
    }

    @Override
    public void resume(int downloadId) throws RemoteException {
        mRxFetch.resume(downloadId);
    }

    @Override
    public void pause(int downloadId) throws RemoteException {
        mRxFetch.pause(downloadId);
    }

    @Override
    public void resumeGroup(int groupId) throws RemoteException {
        mRxFetch.resumeGroup(groupId);
    }

    @Override
    public void pauseGroup(int groupId) throws RemoteException {
        mRxFetch.pauseGroup(groupId);
    }

    @Override
    public void registerDownloadListener(IDownloadListener listener) throws RemoteException {
        synchronized (mDownloadListeners){
            mDownloadListeners.register(listener);
            if (mDownloadListeners.getRegisteredCallbackCount() > 0){
                mRxFetch.addListener(this);
            }
        }

    }

    @Override
    public void unRegisterDownloadListener(IDownloadListener listener) throws RemoteException {
        synchronized (mDownloadListeners){
            mDownloadListeners.unregister(listener);
            if (mDownloadListeners.getRegisteredCallbackCount() == 0){
                mRxFetch.removeListener(this);
            }
        }
    }

    @Override
    public List<DownloadInfo> getDownloadInfo() {
        try {
            return mRxFetch.getDownloads()
                    .asObservable()
                    .flatMapIterable(downloads -> downloads)
                    .map(this::parseDownloadInfo)
                    .toList()
                    .toFuture()
                    .get();
        } catch (InterruptedException | ExecutionException e) {
            e.printStackTrace();
        }
        return Collections.emptyList();
    }

    @Override
    public List<DownloadInfo> getDownloadInfoByGroup(int groupId) {
        try {
            return mRxFetch.getDownloadsInGroup(groupId)
                    .asObservable()
                    .flatMapIterable(downloads -> downloads)
                    .map(this::parseDownloadInfo)
                    .toList()
                    .toFuture()
                    .get();
        } catch (InterruptedException | ExecutionException e) {
            e.printStackTrace();
        }
        return Collections.emptyList();
    }

    @Override
    public DownloadInfo getDownloadById(int id) {
        try {
            return mRxFetch.getDownload(id)
                    .asObservable()
                    .map(this::parseDownloadInfo)
                    .toFuture()
                    .get();
        } catch (InterruptedException | ExecutionException e) {
            e.printStackTrace();
        }
        return null;
    }

    @Override
    public List<DownloadInfo> getDownloadByStatusAndGroup(DownloadStatus status, int groupId) throws RemoteException {
        try {
            return mRxFetch.getDownloadsWithStatus(parseStatus(status))
                    .asObservable()
                    .flatMapIterable(downloads ->downloads)
                    .filter(download -> download.getGroup() == groupId)
                    .map(this::parseDownloadInfo)
                    .toList()
                    .toFuture()
                    .get();
        } catch (InterruptedException | ExecutionException e) {
            e.printStackTrace();
        }
        return Collections.emptyList();
    }

    @Override
    public List<DownloadInfo> getDownloadByStatus(DownloadStatus status) throws RemoteException {
        try {
            return mRxFetch.getDownloadsWithStatus(parseStatus(status))
                    .asObservable()
                    .flatMapIterable(downloads ->downloads)
                    .map(this::parseDownloadInfo)
                    .toList()
                    .toFuture()
                    .get();
        } catch (InterruptedException | ExecutionException e) {
            e.printStackTrace();
        }
        return Collections.emptyList();
    }

    interface Executable {
        void execute(IDownloadListener downloadListener);
    }

    private void execute(Executable executable,int group) {
        synchronized (mDownloadListeners){
            int count = mDownloadListeners.getRegisteredCallbackCount();
            mDownloadListeners.beginBroadcast();
            for (int i = 0 ;i < count;i++){
                try {
                    IDownloadListener downloadListener = mDownloadListeners.getBroadcastItem(i);
                    if (downloadListener.listenGroup() != group){
                        continue;
                    }
                    executable.execute(downloadListener);
                } catch (RemoteException e) {
                    e.printStackTrace();
                }
            }
            mDownloadListeners.finishBroadcast();
        }
    }

    private DownloadInfo parseDownloadInfo(Download download) {
        synchronized (mCacheDownloadInfo) {
            DownloadInfo info = mCacheDownloadInfo.get(download);
            if (info == null) {
                Logger.d("new cache info");
                info = new DownloadInfo();
                mCacheDownloadInfo.put(download,info);
            }
            info.id = download.getId();
            info.progress = download.getProgress();
            info.totalBytes = download.getTotal();
            info.currentBytes = download.getDownloaded();
            info.filePath = download.getFile();
            info.groupId = download.getGroup();
            info.tag = download.getTag();
            info.url = download.getUrl();
            info.status = parseStatus(download.getStatus());
            return info;
        }
    }

    private DownloadStatus parseStatus(@NonNull Status status) {
        switch (status) {
            case NONE:
                return DownloadStatus.NONE;
            case QUEUED:
                return DownloadStatus.QUEUED;
            case DOWNLOADING:
                return DownloadStatus.DOWNLOADING;
            case PAUSED:
                return DownloadStatus.PAUSED;
            case COMPLETED:
                return DownloadStatus.COMPLETED;
            case CANCELLED:
                return DownloadStatus.CANCELLED;
            case FAILED:
                return DownloadStatus.FAILED;
            case REMOVED:
                return DownloadStatus.REMOVED;
            case DELETED:
                return DownloadStatus.DELETED;
            case ADDED:
                return DownloadStatus.ADDED;
            default:
                return DownloadStatus.NONE;
        }
    }
    private Status parseStatus(@NonNull DownloadStatus status) {
        switch (status) {
            case NONE:
                return Status.NONE;
            case QUEUED:
                return Status.QUEUED;
            case DOWNLOADING:
                return Status.DOWNLOADING;
            case PAUSED:
                return Status.PAUSED;
            case COMPLETED:
                return Status.COMPLETED;
            case CANCELLED:
                return Status.CANCELLED;
            case FAILED:
                return Status.FAILED;
            case REMOVED:
                return Status.REMOVED;
            case DELETED:
                return Status.DELETED;
            case ADDED:
                return Status.ADDED;
            default:
                return Status.NONE;
        }
    }


    @Override
    public void onAdded(Download download) {
        Logger.d("onAdded");
        execute(downloadListener -> {
            try {
                downloadListener.onAdded(parseDownloadInfo(download));
            } catch (RemoteException e) {
                e.printStackTrace();
            }
        },download.getGroup());
    }

    @Override
    public void onQueued(Download download, boolean waitingOnNetwork) {
        Logger.d("onQueued");
        execute(downloadListener -> {
            try {
                downloadListener.onQueued(parseDownloadInfo(download),waitingOnNetwork);
            } catch (RemoteException e) {
                e.printStackTrace();
            }
        },download.getGroup());
    }

    @Override
    public void onCompleted(Download download) {
        Logger.d("onCompleted");
        execute(downloadListener -> {
            try {
                downloadListener.onCompleted(parseDownloadInfo(download));
            } catch (RemoteException e) {
                e.printStackTrace();
            }
        },download.getGroup());
    }

    @Override
    public void onError(Download download) {
        Logger.d("onError");
        execute(downloadListener -> {
            try {
                downloadListener.onError(parseDownloadInfo(download));
            } catch (RemoteException e) {
                e.printStackTrace();
            }
        },download.getGroup());
    }

    @Override
    public void onDownloadBlockUpdated(Download download, DownloadBlock downloadBlock, int totalBlocks) {
       Logger.d("onDownloadBlockUpdated ");
    }

    @Override
    public void onProgress(Download download, long etaInMilliSeconds, long downloadedBytesPerSecond) {
        Logger.d("onProgress %d" ,download.getProgress());
        execute(downloadListener -> {
            try {
                downloadListener.onProgress(parseDownloadInfo(download),etaInMilliSeconds,downloadedBytesPerSecond);
            } catch (RemoteException e) {
                e.printStackTrace();
            }
        },download.getGroup());
    }

    @Override
    public void onPaused(Download download) {
        Logger.d("onPaused");
        execute(downloadListener -> {
            try {
                downloadListener.onPaused(parseDownloadInfo(download));
            } catch (RemoteException e) {
                e.printStackTrace();
            }
        },download.getGroup());
    }

    @Override
    public void onResumed(Download download) {
        Logger.d("onResumed");
        execute(downloadListener -> {
            try {
                downloadListener.onResumed(parseDownloadInfo(download));
            } catch (RemoteException e) {
                e.printStackTrace();
            }
        },download.getGroup());
    }

    @Override
    public void onCancelled(Download download) {
        Logger.d("onCancelled");
        execute(downloadListener -> {
            try {
                downloadListener.onCancelled(parseDownloadInfo(download));
            } catch (RemoteException e) {
                e.printStackTrace();
            }
        },download.getGroup());
    }

    @Override
    public void onRemoved(Download download) {
        Logger.d("onRemoved");
        execute(downloadListener -> {
            try {
                downloadListener.onRemoved(parseDownloadInfo(download));
            } catch (RemoteException e) {
                e.printStackTrace();
            }
        },download.getGroup());
    }

    @Override
    public void onDeleted(Download download) {
        Logger.d("onDeleted");
        execute(downloadListener -> {
            try {
                downloadListener.onDeleted(parseDownloadInfo(download));
            } catch (RemoteException e) {
                e.printStackTrace();
            }
        },download.getGroup());
    }
}
`

here is my client test code 
`  @Before
    public void testServiceBefore() throws Exception {
        Context appContext = InstrumentationRegistry.getTargetContext();
        Intent intent = new Intent(appContext, UpgradeService.class);
        intent.setComponent(new ComponentName("com.xxx.xxx", "xxx.xxx.xxx"));
        IBinder binder = mServiceTestRule.bindService(intent);
        mBinderPool = IBinderPool.Stub.asInterface(binder);
        IBinder downloadBinder = mBinderPool.queryBinder(UpgradeConstants.DOWNLOAD_OPS);
        mDownloadOps = IDownloadOps.Stub.asInterface(downloadBinder);
        IBinder packageBinder = mBinderPool.queryBinder(UpgradeConstants.PACKAGE_OPS);
        mPackageOps = IPackageOps.Stub.asInterface(packageBinder);
    }

    @Test
    public void testDownload() throws InterruptedException, RemoteException {
        mDownloadOps.registerDownloadListener(new IDownloadListener.Stub() {
            @Override
            public void onAdded(DownloadInfo download) throws RemoteException {
                Logger.d("onAdded download info is %s",JSONUtils.toJson(download));
            }

            @Override
            public void onQueued(DownloadInfo download, boolean waitingOnNetwork) throws RemoteException {
                Logger.d("onQueued download info is %s",JSONUtils.toJson(download));
            }

            @Override
            public void onCompleted(DownloadInfo download) throws RemoteException {
                Logger.d("onCompleted download info is %s",JSONUtils.toJson(download));
            }

            @Override
            public void onError(DownloadInfo download) throws RemoteException {
                Logger.d("onError download info is %s",JSONUtils.toJson(download));
            }

            @Override
            public void onProgress(DownloadInfo download, long etaInMilliSeconds, long downloadedBytesPerSecond) throws RemoteException {
                Logger.d("onProgress download info is %s",JSONUtils.toJson(download));
            }

            @Override
            public void onPaused(DownloadInfo download) throws RemoteException {
                Logger.d("onPaused download info is %s",JSONUtils.toJson(download));
            }

            @Override
            public void onResumed(DownloadInfo download) throws RemoteException {
                Logger.d("onResumed download info is %s",JSONUtils.toJson(download));
            }

            @Override
            public void onCancelled(DownloadInfo download) throws RemoteException {
                Logger.d("onCancelled download info is %s",JSONUtils.toJson(download));
            }

            @Override
            public void onRemoved(DownloadInfo download) throws RemoteException {
                Logger.d("onRemoved download info is %s",JSONUtils.toJson(download));
            }

            @Override
            public void onDeleted(DownloadInfo download) throws RemoteException {
                Logger.d("onDeleted download info is %s",JSONUtils.toJson(download));
            }

            @Override
            public int listenGroup() throws RemoteException {
                return 0;
            }
        });
        Context context = InstrumentationRegistry.getTargetContext();
        File cacheDir = context.getCacheDir();
        try {
            downloadFile(cacheDir,"example.apk");
        } catch (RemoteException e) {
            e.printStackTrace();
        }

        block();
    }`

and here is my log 
![image](https://user-images.githubusercontent.com/20364956/42641908-3ba44380-8628-11e8-85c7-15be3628ef60.png)

thanks a lot @tonyofrancis

**Comment by kaiv587hh** [comment]
when I call pause(id)  ,I can still receive onProgress callback ,and when I resume ,it return back to previous progress , when I call pause/resume qickly as the code showing 2s period.

**Comment by tonyofrancis** [comment]
@kaiv587hh Can you share the log again with the downloadId???. I am testing on my end.

**Comment by tonyofrancis** [comment]
Just finished doing some tests and was not able to replicate the issue in the current release. What version of Fetch are you using? Tested with latest is 2.1.0-RC14.
This was a known bug in older versions of Fetch.

**Comment by kaiv587hh** [comment]
@tonyofrancis my dependency is 2.1.0-RC13 ,when I use the lib, it's the latest version

**Comment by kaiv587hh** [comment]
@tonyofrancis  I still replicate the bug, can you share your demo code to me ?  in my end ,when called pause(id) , I still receive the progress, and I only download one file to ensure there is no other task . so  when do you call the onProgress ?  receive data ? or writeToFile ?   or write progress to db ? is the data source same of Download object onPause and onProgress called ? so sorry that I am not family to kotlin .

**Comment by kaiv587hh** [comment]
The problem  still exists. hope  soon...

**Comment by tonyofrancis** [comment]
@kaiv587hh  Can you share a sample project. I have been unable to replicate this issue.

**Comment by kaiv587hh** [comment]
my test download path is http://7xawii.com1.z0.glb.clouddn.com/1490232809284f81c7e9c2a4647ce46aff59145fdd3fc.png

simply ,
1. call enque(download) 
2. when got onProgress callback soon call pause(id) ,
3. then kill the app
4. start the app 
5. getDownload
6. resume the downloadId 
7. the download progress is return to 0 

can you add some log when you write to your db ? 

because  the progress of the onProgress is just right ,but the progree of onPause is wrong.

**Comment by kaiv587hh** [comment]
I use breakpoint but it works well,
I am considering if multithread problem ?

**Comment by kaiv587hh** [comment]
do you have email or wechat ? 
for more information to communicate ?

**Comment by kaiv587hh** [comment]
@tonyofrancis ok,  because the lib is  using in my company's  project, so sorry to share the full code , but it's too urgent for me . So I have read your code today . 
but for me , it's not a good idea to read all .I am not familiar than you.

It's probabilistic,  in my end  the probability is more than 50% ,just for small file . 

Is it possible about writing file successful ,but db failed ?

I am wishing if you can support log  ability in every db operation so that I can know what happened in my end.

**Comment by kaiv587hh** [comment]
by the way, the progress is wrong ,while the file has been successfully downloaded as the previous correct progress. I use adb to watch that.

**Comment by tonyofrancis** [comment]
@kaiv587hh I was able to replicate the problem when Fetch uses the Sequential Downloader. The same issue was fixed on the Parallel Downloader a while back.

Working on a patch. In the mean time you can use the Parallel Downloader.
eg
```java
.setHttpDownloader(new OkHttpDownloader(Downloader.FileDownloaderType.PARALLEL))
```

**Comment by kaiv587hh** [comment]
ok,thanks , so will the default downloader be fixed later?

--------------原始邮件--------------
发件人："Tonyo Francis "<notifications@github.com>;
发送时间：2018年7月18日(星期三) 晚上11:37
收件人："tonyofrancis/Fetch" <Fetch@noreply.github.com>;
抄送："kaiv587hh "<zhaokai@cvte.com>;"Mention "<mention@noreply.github.com>;
主题：Re: [tonyofrancis/Fetch] progress return back? (#185)
-----------------------------------

@kaiv587hh I was able to replicate the problem when Fetch uses the Sequential Downloader. The same issue was fixed on the Parallel Downloader a while back.
 
Working on a patch. In the mean time you can use the Parallel Downloader.
 eg
 .setHttpDownloader(new OkHttpDownloader(Downloader.FileDownloaderType.PARALLEL))

**Comment by tonyofrancis** [comment]
hoping to get it fixed today or by tomorrow.

**Comment by tonyofrancis** [comment]
@kaiv587hh  Just published Fetch 2.2.0-RC1. Should now fix this issue. Looking forward to your feedback.

**Comment by kaiv587hh** [comment]
@tonyofrancis  thanks for your support, I will update the lib and test soon.

**Comment by kaiv587hh** [comment]
@tonyofrancis so sad ,when I use the latest lib, the download callback become slow and slow. Does the latest version modify something about callback  speed ,for example ,when I enqueue a download request, the onQueue callback comes so late than before.

**Comment by DennisVanAcker1** [comment]
This issue is still appearing in the latest version using the SequentialFileDownloader. I have debugged a whole day in Fetch and could not find what causes the issue. I'm caching files using a low priority and when i need a file urgent i enqueue it again with a priority set on high (i also cancel& retry the downloads with a lower priority to make sure the high priority one is done first). The download id's of the downloads that appear in onProgress are the same but the progress argument is sometimes lower on the same download (same id) than the first callback with that id. I know that if the file is still QUEUED; the downloadinfo record gets updated in the fetch database and the priorityListProcessor queries the database for any queued downloads. I did not seem like there were double records in the db (which would suprise me). This is definitly a bug in fetch and it's not an easy one to find...

**Comment by DennisVanAcker1** [comment]
@tonyofrancis in the DownloadManagerImpl a new filedownloader gets assigned like this on line 92: currentDownloadsMap[download.id] = fileDownloader. But if there's already a filedownloader object, shouldn't that object be cancelled & cleaned up. I think 2 SequentialFileDownloaders might be running for the same file

**Comment by DennisVanAcker1** [comment]
@tonyofrancis is it possible that two SequantialFileDownloaders are running at the same time for the same download? On line 92 in DownloadManagerImpl, there's this: currentDownloadsMap[download.id] = fileDownloader. But what happens if a downloadManager already existed for that download.id key, what happens to it?

**Comment by DennisVanAcker1** [comment]
for some reason, the downloadmanager logs the same download twice: 
```
DownloadManager starting download DownloadInfo(id=-230652258, namespace='LibGlobalFetchLib', url='https://ep2.eboekhuis.nl/wmDwld.php?uid=5d527ed465952&ean=9789048841790&r=1'
DownloadManager starting download DownloadInfo(id=-230652258, namespace='LibGlobalFetchLib', url='https://ep2.eboekhuis.nl/wmDwld.php?uid=5d527ed465952&ean=9789048841790&r=1'
```

**Comment by DennisVanAcker1** [comment]
My logs in a situation that goes wrong. You can clearly see that DownloadManager logs are printed twice. If you'd ask me, the problem lies somewhere in the start method of DownloadManagerImpl . @tonyofrancis 

```
Enqueued download DownloadInfo(id=-1196903373, namespace='LibGlobalFetchLib', url='https://ep2.eboekhuis.nl/wmDwld.php?uid=5d527ed465952&ean=9789048841790&r=1', file='/data/user/0/nl.bibliotheek.ebooks/files/.kb/publications/b1440db6-723f-4c1c-8a97-50fd7c7cfce2/4c48c02de4e3c9e1a45f472d97197573.epub', group=-872198815, priority=LOW, headers={}, downloaded=0, total=-1, status=QUEUED, error=NONE, networkType=ALL, created=1566476467690, tag=null, enqueueAction=UPDATE_ACCORDINGLY, identifier=0, downloadOnEnqueue=true, extras={}, etaInMilliSeconds=-1, downloadedBytesPerSecond=-1)
Added DownloadInfo(id=-1196903373, namespace='LibGlobalFetchLib', url='https://ep2.eboekhuis.nl/wmDwld.php?uid=5d527ed465952&ean=9789048841790&r=1', file='/data/user/0/nl.bibliotheek.ebooks/files/.kb/publications/b1440db6-723f-4c1c-8a97-50fd7c7cfce2/4c48c02de4e3c9e1a45f472d97197573.epub', group=-872198815, priority=LOW, headers={}, downloaded=0, total=-1, status=QUEUED, error=NONE, networkType=ALL, created=1566476467690, tag=null, enqueueAction=UPDATE_ACCORDINGLY, identifier=0, downloadOnEnqueue=true, extras={}, etaInMilliSeconds=-1, downloadedBytesPerSecond=-1)
Queued DownloadInfo(id=-1196903373, namespace='LibGlobalFetchLib', url='https://ep2.eboekhuis.nl/wmDwld.php?uid=5d527ed465952&ean=9789048841790&r=1'
Updated download DownloadInfo(id=-1196903373, namespace='LibGlobalFetchLib', url='https://ep2.eboekhuis.nl/wmDwld.php?uid=5d527ed465952&ean=9789048841790&r=1', 
Added DownloadInfo(id=-1196903373, namespace='LibGlobalFetchLib', url='https://ep2.eboekhuis.nl/wmDwld.php?uid=5d527ed465952&ean=9789048841790&r=1', file='/data/user/0/nl.bibliotheek.ebooks/files/.kb/publications/b1440db6-723f-4c1c-8a97-50fd7c7cfce2/4c48c02de4e3c9e1a45f472d97197573.epub', group=-872198815, priority=HIGH, headers={}, downloaded=0, total=-1, status=QUEUED, error=NONE, networkType=ALL, created=1566476472097, tag=null, enqueueAction=UPDATE_ACCORDINGLY, identifier=0, downloadOnEnqueue=true, extras={}, etaInMilliSeconds=-1, downloadedBytesPerSecond=-1)
Queued DownloadInfo(id=-1196903373, namespace='LibGlobalFetchLib', url='https://ep2.eboekhuis.nl/wmDwld.php?uid=5d527ed465952&ean=9789048841790&r=1', 
DownloadManager starting download DownloadInfo(id=-1196903373, namespace='LibGlobalFetchLib', url='https://ep2.eboekhuis.nl/wmDwld.php?uid=5d527ed465952&ean=9789048841790&r=1', file='/data/user/0/nl.bibliotheek.ebooks/files/.kb/publications/b1440db6-723f-4c1c-8a97-50fd7c7cfce2/4c48c02de4e3c9e1a45f472d97197573.epub', group=-872198815, priority=LOW, headers={}, downloaded=0, total=-1, status=QUEUED, error=NONE, networkType=ALL, created=1566476467690, tag=null, enqueueAction=UPDATE_ACCORDINGLY, identifier=0, downloadOnEnqueue=true, extras={}, etaInMilliSeconds=-1, downloadedBytesPerSecond=-1)
DownloadManager starting download DownloadInfo(id=-1196903373, namespace='LibGlobalFetchLib', url='https://ep2.eboekhuis.nl/wmDwld.php?uid=5d527ed465952&ean=9789048841790&r=1', file='/data/user/0/nl.bibliotheek.ebooks/files/.kb/publications/b1440db6-723f-4c1c-8a97-50fd7c7cfce2/4c48c02de4e3c9e1a45f472d97197573.epub', group=-872198815, priority=HIGH, headers={}, downloaded=0, total=-1, status=QUEUED, error=NONE, networkType=ALL, created=1566476472097, tag=null, enqueueAction=UPDATE_ACCORDINGLY, identifier=0, downloadOnEnqueue=true, extras={}, etaInMilliSeconds=-1, downloadedBytesPerSecond=-1)
FileDownloader starting Download DownloadInfo(id=-1196903373, namespace='LibGlobalFetchLib', url='https://ep2.eboekhuis.nl/wmDwld.php?uid=5d527ed465952&ean=9789048841790&r=1', file='/data/user/0/nl.bibliotheek.ebooks/files/.kb/publications/b1440db6-723f-4c1c-8a97-50fd7c7cfce2/4c48c02de4e3c9e1a45f472d97197573.epub', group=-872198815, priority=LOW, headers={}, downloaded=0, total=2986610, status=QUEUED, error=NONE, networkType=ALL, created=1566476467690, tag=null, enqueueAction=UPDATE_ACCORDINGLY, identifier=0, downloadOnEnqueue=true, extras={}, etaInMilliSeconds=-1, downloadedBytesPerSecond=-1)
FileDownloader starting Download DownloadInfo(id=-1196903373, namespace='LibGlobalFetchLib', url='https://ep2.eboekhuis.nl/wmDwld.php?uid=5d527ed465952&ean=9789048841790&r=1',
```

**Comment by DennisVanAcker1** [comment]
Update: this might be a threading issue.
The breakpoint on  downloadCounter += 1 breaks once, while the log "DownloadManager starting download" is printed twice.

**Comment by DennisVanAcker1** [comment]
@tonyofrancis I think i found the problem. I managed to copy the Fetch sourcefiles into my own project to be able to debug and place my own logs into Fetch. The issue has to do with timing. 

The DownloadManager start() method gets called twice, which makes sense because the old download started and gets cancelled and the new one also starts...

The problem is that any of the download threads are started after the key gets added again by starting the second download! Therefore, the first download thread sees that there's a key available and this returns true in the start method of the DownloadManagerImpl: 

`if (currentDownloadsMap.containsKey(download.id))`

  => filedownloader gets created twice!

To solve the problem in my project, i currently have to sequentially download files. I hope you can integrate a fix in a new version. If you have any questions or need more info, please let me know!

 My logs:


```
priopriorityIteratorRunnable run

priorityIteratorRunnable prioritylist: DownloadInfo(id=-19924960, namespace='LibGlobalFetchLib', url='https://ep2.eboekhuis.nl/wmDwld.php?uid=5d527ed465952&ean=9789048841790&r=1', file='/data/user/0/nl.bibliotheek.ebooks/files/.kb/publications/e243f186-63b2-471e-a4e8-4f7a718b8f59/4c48c02de4e3c9e1a45f472d97197573.epub', group=-872198815, priority=LOW, headers={}, downloaded=0, total=-1, status=QUEUED, error=NONE, networkType=ALL, created=1566567733026, tag=null, enqueueAction=UPDATE_ACCORDINGLY, identifier=0, downloadOnEnqueue=true, extras={}, autoRetryMaxAttempts=0, autoRetryAttempts=0, etaInMilliSeconds=-1, downloadedBytesPerSecond=-1)
DownloadManager start method called for DownloadInfo(id=-19924960, namespace='LibGlobalFetchLib', url='https://ep2.eboekhuis.nl/wmDwld.php?uid=5d527ed465952&ean=9789048841790&r=1', file='/data/user/0/nl.bibliotheek.ebooks/files/.kb/publications/e243f186-63b2-471e-a4e8-4f7a718b8f59/4c48c02de4e3c9e1a45f472d97197573.epub', group=-872198815, priority=LOW, headers={}, downloaded=0, total=-1, status=QUEUED, error=NONE, networkType=ALL, created=1566567733026, tag=null, enqueueAction=UPDATE_ACCORDINGLY, identifier=0, downloadOnEnqueue=true, extras={}, autoRetryMaxAttempts=0, autoRetryAttempts=0, etaInMilliSeconds=-1, downloadedBytesPerSecond=-1)
DownloadManager key: -19924960 added

priorityIteratorRunnable run
priorityIteratorRunnable prioritylist: DownloadInfo(id=-19924960, namespace='LibGlobalFetchLib', url='https://ep2.eboekhuis.nl/wmDwld.php?uid=5d527ed465952&ean=9789048841790&r=1', file='/data/user/0/nl.bibliotheek.ebooks/files/.kb/publications/e243f186-63b2-471e-a4e8-4f7a718b8f59/4c48c02de4e3c9e1a45f472d97197573.epub', group=-872198815, priority=LOW, headers={}, downloaded=0, total=-1, status=QUEUED, error=NONE, networkType=ALL, created=1566567733026, tag=null, enqueueAction=UPDATE_ACCORDINGLY, identifier=0, downloadOnEnqueue=true, extras={}, autoRetryMaxAttempts=0, autoRetryAttempts=0, etaInMilliSeconds=-1, downloadedBytesPerSecond=-1)
downloadManager start not called
cancelDownloadNoLock: key: -19924960 removed from currentDownloadsMap 1
DownloadManager could not cancel, filedownloader is null
cancelDownloadsIfDownloading DownloadInfo(id=-19924960, namespace='LibGlobalFetchLib', url='https://ep2.eboekhuis.nl/wmDwld.php?uid=5d527ed465952&ean=9789048841790&r=1', file='/data/user/0/nl.bibliotheek.ebooks/files/.kb/publications/e243f186-63b2-471e-a4e8-4f7a718b8f59/4c48c02de4e3c9e1a45f472d97197573.epub', group=-872198815, priority=HIGH, headers={}, downloaded=0, total=-1, status=NONE, error=NONE, networkType=ALL, created=1566567736475, tag=null, enqueueAction=UPDATE_ACCORDINGLY, identifier=0, downloadOnEnqueue=true, extras={}, autoRetryMaxAttempts=0, autoRetryAttempts=0, etaInMilliSeconds=-1, downloadedBytesPerSecond=-1)

priorityIteratorRunnable run
priorityIteratorRunnable prioritylist: DownloadInfo(id=-19924960, namespace='LibGlobalFetchLib', url='https://ep2.eboekhuis.nl/wmDwld.php?uid=5d527ed465952&ean=9789048841790&r=1', file='/data/user/0/nl.bibliotheek.ebooks/files/.kb/publications/e243f186-63b2-471e-a4e8-4f7a718b8f59/4c48c02de4e3c9e1a45f472d97197573.epub', group=-872198815, priority=HIGH, headers={}, downloaded=0, total=-1, status=QUEUED, error=NONE, networkType=ALL, created=1566567736475, tag=null, enqueueAction=UPDATE_ACCORDINGLY, identifier=0, downloadOnEnqueue=true, extras={}, autoRetryMaxAttempts=0, autoRetryAttempts=0, etaInMilliSeconds=-1, downloadedBytesPerSecond=-1)
DownloadManager start method called for DownloadInfo(id=-19924960, namespace='LibGlobalFetchLib', url='https://ep2.eboekhuis.nl/wmDwld.php?uid=5d527ed465952&ean=9789048841790&r=1', file='/data/user/0/nl.bibliotheek.ebooks/files/.kb/publications/e243f186-63b2-471e-a4e8-4f7a718b8f59/4c48c02de4e3c9e1a45f472d97197573.epub', group=-872198815, priority=HIGH, headers={}, downloaded=0, total=-1, status=QUEUED, error=NONE, networkType=ALL, created=1566567736475, tag=null, enqueueAction=UPDATE_ACCORDINGLY, identifier=0, downloadOnEnqueue=true, extras={}, autoRetryMaxAttempts=0, autoRetryAttempts=0, etaInMilliSeconds=-1, downloadedBytesPerSecond=-1)
DownloadManager key: -19924960 added
DownloadManager containsKey:-19924960
DownloadManager starting download DownloadInfo(id=-19924960, namespace='LibGlobalFetchLib', url='https://ep2.eboekhuis.nl/wmDwld.php?uid=5d527ed465952&ean=9789048841790&r=1', file='/data/user/0/nl.bibliotheek.ebooks/files/.kb/publications/e243f186-63b2-471e-a4e8-4f7a718b8f59/4c48c02de4e3c9e1a45f472d97197573.epub', group=-872198815, priority=LOW, headers={}, downloaded=0, total=-1, status=QUEUED, error=NONE, networkType=ALL, created=1566567733026, tag=null, enqueueAction=UPDATE_ACCORDINGLY, identifier=0, downloadOnEnqueue=true, extras={}, autoRetryMaxAttempts=0, autoRetryAttempts=0, etaInMilliSeconds=-1, downloadedBytesPerSecond=-1)


priorityIteratorRunnable run
priorityIteratorRunnable prioritylist: DownloadInfo(id=-19924960, namespace='LibGlobalFetchLib', url='https://ep2.eboekhuis.nl/wmDwld.php?uid=5d527ed465952&ean=9789048841790&r=1', file='/data/user/0/nl.bibliotheek.ebooks/files/.kb/publications/e243f186-63b2-471e-a4e8-4f7a718b8f59/4c48c02de4e3c9e1a45f472d97197573.epub', group=-872198815, priority=HIGH, headers={}, downloaded=0, total=-1, status=QUEUED, error=NONE, networkType=ALL, created=1566567736475, tag=null, enqueueAction=UPDATE_ACCORDINGLY, identifier=0, downloadOnEnqueue=true, extras={}, autoRetryMaxAttempts=0, autoRetryAttempts=0, etaInMilliSeconds=-1, downloadedBytesPerSecond=-1)
downloadManager start not called

priorityIteratorRunnable run
priorityIteratorRunnable prioritylist: DownloadInfo(id=-19924960, namespace='LibGlobalFetchLib', url='https://ep2.eboekhuis.nl/wmDwld.php?uid=5d527ed465952&ean=9789048841790&r=1', file='/data/user/0/nl.bibliotheek.ebooks/files/.kb/publications/e243f186-63b2-471e-a4e8-4f7a718b8f59/4c48c02de4e3c9e1a45f472d97197573.epub', group=-872198815, priority=HIGH, headers={}, downloaded=0, total=-1, status=QUEUED, error=NONE, networkType=ALL, created=1566567736475, tag=null, enqueueAction=UPDATE_ACCORDINGLY, identifier=0, downloadOnEnqueue=true, extras={}, autoRetryMaxAttempts=0, autoRetryAttempts=0, etaInMilliSeconds=-1, downloadedBytesPerSecond=-1)
downloadManager start not called

priorityIteratorRunnable run
priorityIteratorRunnable prioritylist: DownloadInfo(id=-19924960, namespace='LibGlobalFetchLib', url='https://ep2.eboekhuis.nl/wmDwld.php?uid=5d527ed465952&ean=9789048841790&r=1', file='/data/user/0/nl.bibliotheek.ebooks/files/.kb/publications/e243f186-63b2-471e-a4e8-4f7a718b8f59/4c48c02de4e3c9e1a45f472d97197573.epub', group=-872198815, priority=HIGH, headers={}, downloaded=0, total=-1, status=QUEUED, error=NONE, networkType=ALL, created=1566567736475, tag=null, enqueueAction=UPDATE_ACCORDINGLY, identifier=0, downloadOnEnqueue=true, extras={}, autoRetryMaxAttempts=0, autoRetryAttempts=0, etaInMilliSeconds=-1, downloadedBytesPerSecond=-1)
downloadManager start not called

DownloadManager containsKey:-19924960
DownloadManager starting download DownloadInfo(id=-19924960, namespace='LibGlobalFetchLib', url='https://ep2.eboekhuis.nl/wmDwld.php?uid=5d527ed465952&ean=9789048841790&r=1', file='/data/user/0/nl.bibliotheek.ebooks/files/.kb/publications/e243f186-63b2-471e-a4e8-4f7a718b8f59/4c48c02de4e3c9e1a45f472d97197573.epub', group=-872198815, priority=HIGH, headers={}, downloaded=0, total=-1, status=QUEUED, error=NONE, networkType=ALL, created=1566567736475, tag=null, enqueueAction=UPDATE_ACCORDINGLY, identifier=0, downloadOnEnqueue=true, extras={}, autoRetryMaxAttempts=0, autoRetryAttempts=0, etaInMilliSeconds=-1, downloadedBytesPerSecond=-1)

priorityIteratorRunnable run
priorityIteratorRunnable prioritylist: DownloadInfo(id=-19924960, namespace='LibGlobalFetchLib', url='https://ep2.eboekhuis.nl/wmDwld.php?uid=5d527ed465952&ean=9789048841790&r=1', file='/data/user/0/nl.bibliotheek.ebooks/files/.kb/publications/e243f186-63b2-471e-a4e8-4f7a718b8f59/4c48c02de4e3c9e1a45f472d97197573.epub', group=-872198815, priority=HIGH, headers={}, downloaded=0, total=-1, status=QUEUED, error=NONE, networkType=ALL, created=1566567736475, tag=null, enqueueAction=UPDATE_ACCORDINGLY, identifier=0, downloadOnEnqueue=true, extras={}, autoRetryMaxAttempts=0, autoRetryAttempts=0, etaInMilliSeconds=-1, downloadedBytesPerSecond=-1)
downloadManager start not called

priorityIteratorRunnable run
fileDownloader: 187729859 run:-19924960
removeDownloadMappings

priorityIteratorRunnable run
fileDownloader: 222481756 run:-19924960
priorityIteratorRunnable run
```

**Comment by tonyofrancis** [comment]
@DennisVanAcker1 are you till interested in providing a fix?? Just catching up on issues.

**Comment by DennisVanAcker1** [comment]
I spent alot of time in actually debugging this and finding out what causes the issue during working hours. This issue is not on the agenda of the company i'm working at so i can't put anymore time into this i'm afraid
